[application]
name = "Marvin Light Control"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "MLC"

[web.watcher]
index_on_404 = true

[web.resource]
style = [
    "./assets/style.css",
    "./assets/configure.css",
    "./assets/program.css",
    "./assets/project_selection.css",
]

[web.resource.dev]